cloud:
  aws:
    credentials:
      access-key: AKIA3NYW4QJCPZ5NFGHR
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: elasticbeanstalk-us-east-1-785490149956


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

